name: Template
version: 1.0.0
main: org.example.Plugin
description: An example plugin
author: Esoteric Enderman
website: https://gitlab.com/esoteric-templates/templates/template-maven-minecraft-plugin
api-version: '1.20'
